version: 2.1
jobs:
  build_hw01:
    docker:
    - image: 'circleci/openjdk:latest'
    steps:
    - checkout
    - run: ls -la
    - run: cd hw01 && mvn test
    - store_test_results:
        path: hw01/target/surefire-reports
    - store_artifacts:
        path: hw01/target/classes
workflows:
 version: 2.1
 main:
    jobs:
       - build_hw01
