version: 2.1
jobs:
 build:
   docker:
   - image: 'circleci/openjdk:latest'
   steps:
   - checkout
   - run: ls -la
   - run: cd hw01 && mvn test
   - store_test_results:
       path: hw01/target/surefire-reports
